CC = gcc
CFLAGS = -Wall -Wextra -std=c99 -g -Iinclude -fopenmp
TARGET = deque

SOURCES = src/main.c src/node.c src/deque.c

$(TARGET): $(SOURCES)
	$(CC) $(CFLAGS) -o $(TARGET) $(SOURCES)

clean:
	rm -f $(TARGET)

run: $(TARGET)
	./$(TARGET)

.PHONY: clean run